<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Company>Nexus</Company>
    <Product>Nexus for Windows</Product>
    <Copyright>MIT License</Copyright>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1416;CS1998;NU1701</NoWarn>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
